spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all                        # ensure full commit
      retries: 5                       # retry logic for failure recovery
      compression-type: snappy        # faster and compact
      batch-size: 16384               # buffer batching (16 KB)
      linger-ms: 5                    # delay to allow batching
    consumer:
      group-id: url-shortener-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.faang.model"
        max.poll.records: 500
        max.poll.interval.ms: 300000

    listener:
      ack-mode: manual_immediate
      concurrency: 16
    template:
      default-topic: url-events
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      timeout: 10s
      lettuce:
        shutdown-timeout: 100ms
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

    mongodb:
      uri: mongodb\://localhost\:27017/mongo
      username: root
      password: root
      auto-index-creation: true
  application:
    name: URL-Shortening-Service



management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true


logging:
  level:
    io.netty: DEBUG
    org.apache.kafka: WARN
    org.springframework.kafka: info
